# Generated by Django 3.2.9 on 2021-11-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('office_id', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=20)),
                ('create_on', models.DateTimeField()),
            ],
        ),
    ]
