# Generated by Django 3.2.9 on 2021-11-28 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('seral_no', models.CharField(max_length=200)),
                ('po_no', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('status', models.IntegerField()),
                ('create_on', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.category')),
            ],
        ),
        migrations.CreateModel(
            name='Products_assing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaf_no', models.CharField(max_length=255)),
                ('office_location', models.CharField(max_length=200)),
                ('asset_code', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('remarks', models.TextField()),
                ('assign_date', models.DateTimeField()),
                ('create_on', models.DateTimeField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.employee')),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
